{{- if not .Values.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "metabase.fullname" . }}-database
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "metabase.labels" . | indent 4 }}
type: Opaque
data:
  {{- if .Values.database.connectionURI }}
  connectionURI: {{ .Values.database.connectionURI | b64enc | quote }}
  {{- else }}
  username: {{ .Values.database.username | b64enc | quote }}
  password: {{ .Values.database.password | b64enc | quote }}
  {{- end }}
{{- end }}